repos:
-   repo: local
    hooks:
    -   id: dotnet-format
        name: dotnet format (.NET 6 SDK)
        language: system
        # Change the solution path if using this project as a template
        entry: dotnet format unity-base-template.sln --verify-no-changes --severity info --include

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
        types: [c#]
    -   id: mixed-line-ending
        types: [c#]
    -   id: no-commit-to-branch
    -   id: trailing-whitespace
        types: [c#]
