name: dotnet-format-whitespace

on:
  pull_request:
    branches: [main]

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: dotnet format whitespace Assets/Scripts --folder --verify-no-changes --verbosity detailed
