name: dotnet-format

on:
  pull_request:
    branches: [main]

jobs:
  dotnet-format:
    name: dotnet format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: dotnet format whitespace --folder Assets/Scripts --verify-no-changes
